In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df = pd.read_csv('indian_tech_career_intelligence_2026.csv')
df.head()

,job_title,job_category,company_name,company_size,industry,company_type,location_city,location_state,location_country,work_mode,...,application_deadline,source_platform,applicant_count,job_benefits,technical_domain,interview_difficulty,probation_period,shift_type,is_active,career_growth_index
0,Machine Learning Engineer,AI / ML Engineering,TCS,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,On-site,...,16-03-2026,LinkedIn,193,"Stock Options (ESOPs), Free Meals, Remote Firs...",Core Applied Machine Learning,Medium,3 Months,Flexible Shift,False,85%
1,Full Stack Developer,Web Development,Ola Electric,"1,000-5,000 employees",Information Technology,Tech Startup,Gurgaon,Haryana,India,Remote,...,01-03-2026,AmbitionBox,465,"Paid Time Off, Medical Cover, Annual Bonus",Frontend & Backend Engineering,Easy,3 Months,Flexible Shift,True,65%
2,Web Development Intern,Web Development,Cognizant,"10,000+ employees",Information Technology,Top MNC,Pune,Maharashtra,India,Remote,...,07-02-2026,Glassdoor,77,"Paid Time Off, Medical Cover, Annual Bonus",Frontend & Backend Engineering,Medium,6 Months,Flexible Shift,True,70%
3,DevOps Intern,DevOps Core,Infosys,"10,000+ employees",Information Technology,Top MNC,Gurgaon,Haryana,India,Remote,...,14-06-2026,AmbitionBox,387,"Health Insurance, Flexible Hours, Work from Ho...",Cloud & Infrastructure Systems,Medium,3 Months,Day Shift,True,84%
4,Cybersecurity Analyst,Cybersecurity,Swiggy,"1,000-5,000 employees",Information Technology,Tech Startup,Bangalore,Karnataka,India,On-site,...,22-06-2026,AmbitionBox,27,"Health Insurance, Flexible Hours, Work from Ho...",Network & Information Security,Hard,NaN,Day Shift,True,82%

DATA INSPECTION

In [4]:
df.columns.tolist()

['job_title',
 'job_category',
 'company_name',
 'company_size',
 'industry',
 'company_type',
 'location_city',
 'location_state',
 'location_country',
 'work_mode',
 'salary_minimum',
 'salary_maximum',
 'salary_currency',
 'stipend_amount',
 'experience_level',
 'experience_required',
 'education_required',
 'employment_type',
 'contract_type',
 'skills_extracted',
 'skill_count',
 'job_description',
 'posted_date',
 'application_deadline',
 'source_platform',
 'applicant_count',
 'job_benefits',
 'technical_domain',
 'interview_difficulty',
 'probation_period',
 'shift_type',
 'is_active',
 'career_growth_index']

In [54]:
df['average_salary'] = df['salary_minimum'] + df['salary_minimum'] / 2
df['average_salary'].head()

0    455016.0
1    490149.0
2    823602.0
3    579610.5
4    766168.5
Name: average_salary, dtype: float64

In [60]:
df.dtypes

job_title                   str
job_category                str
company_name                str
company_size                str
industry                    str
company_type                str
location_city               str
location_state              str
location_country            str
salary_minimum            int64
salary_maximum            int64
salary_currency             str
stipend_amount            int64
experience_level            str
experience_required         str
education_required          str
employment_type             str
contract_type               str
skills_extracted            str
skill_count               int64
job_description             str
posted_date                 str
application_deadline        str
source_platform             str
applicant_count           int64
job_benefits                str
technical_domain            str
interview_difficulty        str
probation_period            str
shift_type                  str
is_active                  bool
career_growth_index       Int64
average_salary          float64
dtype: object

In [61]:
df.shape

(100000, 33)

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 33 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   job_title             100000 non-null  str
 1   job_category          100000 non-null  str
 2   company_name          100000 non-null  str
 3   company_size          100000 non-null  str
 4   industry              100000 non-null  str
 5   company_type          100000 non-null  str
 6   location_city         100000 non-null  str
 7   location_state        100000 non-null  str
 8   location_country      100000 non-null  str
 9   salary_minimum        100000 non-null  int64
 10  salary_maximum        100000 non-null  int64
 11  salary_currency       100000 non-null  str
 12  stipend_amount        100000 non-null  int64
 13  experience_level      100000 non-null  str
 14  experience_required   100000 non-null  str
 15  education_required    100000 non-null  str
 16  employment_type       100000 non-null  str
 17  contract_type         100000 non-null  str
 18  skills_extracted      100000 non-null  str
 19  skill_count           100000 non-null  int64
 20  job_description       100000 non-null  str
 21  posted_date           100000 non-null  str
 22  application_deadline  100000 non-null  str
 23  source_platform       100000 non-null  str
 24  applicant_count       100000 non-null  int64
 25  job_benefits          100000 non-null  str
 26  technical_domain      100000 non-null  str
 27  interview_difficulty  100000 non-null  str
 28  probation_period      100000 non-null  str
 29  shift_type            100000 non-null  str
 30  is_active             100000 non-null  bool
 31  career_growth_index   100000 non-null  Int64
 32  average_salary        100000 non-null  float64
dtypes: Int64(1), bool(1), float64(1), int64(5), str(25)
memory usage: 24.6 MB

HANDLING MISSING VALUE

In [63]:
df.isna().sum()

job_title               0
job_category            0
company_name            0
company_size            0
industry                0
company_type            0
location_city           0
location_state          0
location_country        0
salary_minimum          0
salary_maximum          0
salary_currency         0
stipend_amount          0
experience_level        0
experience_required     0
education_required      0
employment_type         0
contract_type           0
skills_extracted        0
skill_count             0
job_description         0
posted_date             0
application_deadline    0
source_platform         0
applicant_count         0
job_benefits            0
technical_domain        0
interview_difficulty    0
probation_period        0
shift_type              0
is_active               0
career_growth_index     0
average_salary          0
dtype: int64

In [ ]:
df.isna().sum()

job_title                   0
job_category                0
company_name                0
company_size                0
industry                    0
company_type                0
location_city               0
location_state              0
location_country            0
salary_minimum              0
salary_maximum              0
salary_currency             0
stipend_amount              0
experience_level            0
experience_required         0
education_required          0
employment_type             0
contract_type               0
skills_extracted            0
skill_count                 0
job_description             0
posted_date                 0
application_deadline        0
source_platform             0
applicant_count             0
job_benefits                0
technical_domain            0
interview_difficulty        0
probation_period        33499
shift_type                  0
is_active                   0
career_growth_index         0
dtype: int64

In [ ]:
df.isnull().sum()

job_title                   0
job_category                0
company_name                0
company_size                0
industry                    0
company_type                0
location_city               0
location_state              0
location_country            0
salary_minimum              0
salary_maximum              0
salary_currency             0
stipend_amount              0
experience_level            0
experience_required         0
education_required          0
employment_type             0
contract_type               0
skills_extracted            0
skill_count                 0
job_description             0
posted_date                 0
application_deadline        0
source_platform             0
applicant_count             0
job_benefits                0
technical_domain            0
interview_difficulty        0
probation_period        33499
shift_type                  0
is_active                   0
career_growth_index         0
dtype: int64

In [ ]:
df['probation_period'].unique()

<StringArray>
['3 Months', '6 Months', nan]
Length: 3, dtype: str

In [ ]:
df['probation_period'] = df['probation_period'].fillna(df['probation_period'].mode()[0])
df['probation_period'].isnull().sum()

np.int64(0)

In [ ]:
df.isna().sum()

job_title               0
job_category            0
company_name            0
company_size            0
industry                0
company_type            0
location_city           0
location_state          0
location_country        0
salary_minimum          0
salary_maximum          0
salary_currency         0
stipend_amount          0
experience_level        0
experience_required     0
education_required      0
employment_type         0
contract_type           0
skills_extracted        0
skill_count             0
job_description         0
posted_date             0
application_deadline    0
source_platform         0
applicant_count         0
job_benefits            0
technical_domain        0
interview_difficulty    0
probation_period        0
shift_type              0
is_active               0
career_growth_index     0
dtype: int64

HANDLING INCONSISTENT FORMATE

In [ ]:
for col in df.columns:
    print(f"{col}: {df[col].unique()}")

job_title: <StringArray>
[  'Machine Learning Engineer',        'Full Stack Developer',
      'Web Development Intern',               'DevOps Intern',
       'Cybersecurity Analyst',   'Site Reliability Engineer',
 'Cloud Infrastructure Intern',       'Data Analytics Intern',
        'Azure Cloud Engineer',           'Platform Engineer',
             'React Developer',               'Data Engineer',
          'Penetration Tester',                 'SOC Analyst',
           'Frontend Engineer',       'Cloud DevOps Engineer',
              'Data Scientist',     'AWS Solutions Architect',
            'Business Analyst',          'AI Research Intern',
    'Computer Vision Engineer',             'Security Intern',
               'LLM Developer',           'Backend Developer']
Length: 24, dtype: str
job_category: <StringArray>
['AI / ML Engineering',     'Web Development',         'DevOps Core',
       'Cybersecurity',  'Cloud Architecture',        'Data Science']
Length: 6, dtype: str
company_name: <StringArray>
[          'TCS',  'Ola Electric',     'Cognizant',       'Infosys',
        'Swiggy',       'HCLTech',         'Paytm',        'Zomato',
          'Cred',         'Wipro', 'Tech Mahindra',      'Razorpay']
Length: 12, dtype: str
company_size: <StringArray>
[    '10,000+ employees', '1,000-5,000 employees',     '100-500 employees',
   '500-1,000 employees']
Length: 4, dtype: str
industry: <StringArray>
['Information Technology']
Length: 1, dtype: str
company_type: <StringArray>
['Top MNC', 'Tech Startup', 'Fintech Unicorn']
Length: 3, dtype: str
location_city: <StringArray>
['Delhi NCR',   'Gurgaon',      'Pune', 'Bangalore',   'Chennai',    'Mumbai',
 'Hyderabad',     'Noida']
Length: 8, dtype: str
location_state: <StringArray>
[        'Delhi',       'Haryana',   'Maharashtra',     'Karnataka',
    'Tamil Nadu',     'Telangana', 'Uttar Pradesh']
Length: 7, dtype: str
location_country: <StringArray>
['India']
Length: 1, dtype: str
salary_minimum: [303344 326766 549068 ... 311878 340435 592542]
salary_maximum: [1696925 1714068 1235656 ...  889572 1204158 1538666]
salary_currency: <StringArray>
['INR']
Length: 1, dtype: str
stipend_amount: [32688 30683 39874 ... 33123 38895 16496]
experience_level: <StringArray>
['Mid-Senior Level', 'Freshers / Entry Level']
Length: 2, dtype: str
experience_required: <StringArray>
['2-4 Years', '0-1 Years']
Length: 2, dtype: str
education_required: <StringArray>
['MCA / MSc', 'Bachelor's Degree', 'B.E. / B.Tech']
Length: 3, dtype: str
employment_type: <StringArray>
['Full-time', 'Internship']
Length: 2, dtype: str
contract_type: <StringArray>
['Permanent', 'Contractual']
Length: 2, dtype: str
skills_extracted: <StringArray>
[     'Python, PyTorch, TensorFlow, Scikit-Learn, OpenAI API, HuggingFace',
   'HTML, CSS, JavaScript, React, Node.js, Express, MongoDB, Tailwind CSS',
               'Docker, Kubernetes, Jenkins, CI/CD, Linux, Terraform, Git',
 'Network Security, Wireshark, Metasploit, Linux, OWASP Top 10, Firewalls',
           'AWS, Azure, CloudFormation, IAM, EC2, S3, Architecture Design',
                    'Python, SQL, Tableau, Power BI, Pandas, NumPy, Excel']
Length: 6, dtype: str
skill_count: [6 8 7]
job_description: <StringArray>
[  '<p>We are hiring a passionate Machine Learning Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
        '<p>We are hiring a passionate Full Stack Developer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
      '<p>We are hiring a passionate Web Development Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
               '<p>We are hiring a passionate DevOps Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
       '<p>We are hiring a passionate Cybersecurity Analyst to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
   '<p>We are hiring a passionate Site Reliability Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
 '<p>We are hiring a passionate Cloud Infrastructure Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
       '<p>We are hiring a passionate Data Analytics Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
        '<p>We are hiring a passionate Azure Cloud Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
           '<p>We are hiring a passionate Platform Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
             '<p>We are hiring a passionate React Developer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
               '<p>We are hiring a passionate Data Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
          '<p>We are hiring a passionate Penetration Tester to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
                 '<p>We are hiring a passionate SOC Analyst to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
           '<p>We are hiring a passionate Frontend Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
       '<p>We are hiring a passionate Cloud DevOps Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
              '<p>We are hiring a passionate Data Scientist to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
     '<p>We are hiring a passionate AWS Solutions Architect to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
            '<p>We are hiring a passionate Business Analyst to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
          '<p>We are hiring a passionate AI Research Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
    '<p>We are hiring a passionate Computer Vision Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
             '<p>We are hiring a passionate Security Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
               '<p>We are hiring a passionate LLM Developer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
           '<p>We are hiring a passionate Backend Developer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>']
Length: 24, dtype: str
posted_date: <StringArray>
['14-02-2026', '30-01-2026', '08-01-2026', '15-05-2026', '23-05-2026',
 '03-01-2026', '11-03-2026', '28-02-2026', '21-05-2026', '28-05-2026',
 ...
 '10-05-2026', '20-05-2026', '12-01-2026', '16-04-2026', '07-02-2026',
 '08-03-2026', '10-04-2026', '16-03-2026', '12-02-2026', '27-02-2026']
Length: 150, dtype: str
application_deadline: <StringArray>
['16-03-2026', '01-03-2026', '07-02-2026', '14-06-2026', '22-06-2026',
 '02-02-2026', '10-04-2026', '30-03-2026', '20-06-2026', '27-06-2026',
 ...
 '09-06-2026', '19-06-2026', '11-02-2026', '16-05-2026', '09-03-2026',
 '07-04-2026', '10-05-2026', '15-04-2026', '14-03-2026', '29-03-2026']
Length: 150, dtype: str
source_platform: <StringArray>
['LinkedIn', 'AmbitionBox', 'Glassdoor', 'Naukri.com', 'Indeed']
Length: 5, dtype: str
applicant_count: [193 465  77 387  27 385 243 364 311 210 117  35 134 451  22 314 177 362
 285  40 218 304 346 468 416 450 434  23 219 198 358  82 224 202  74 372
 138  84 183 388 391 209 195 341  64 433 378 354 381 429 384 365 109 184
  28  79 423 127 136 170 357  62  93 112 310 469 425 137 275 248  15 379
  18 467 439 168 206 299 348 214 142 420 345 187 466 323 352 240 282  26
 185 426 437 417 431 247  92 228 292 302 325 236 126 427  86 114 143 178
 338 105 111  60 110 197 151 286 180 139 252 280 355 371 122 268  88 464
  96 158 200 330 239  24 303 232  25 290  73  43 172 146 119 144 246 435
 300  21  69 470 389 237  20 376  55 235 270  31 284 307  39  57 478 274
 344 446  87 148  78 336 100 430 412 404 192 316  33  19 153 272  17 410
 411 155  94 440 229 223 396 333  66 342 188 301 132 250 251 293 370 382
 104 125 179  76 176 129 222 169 363 238 215 393 265 339 140 123 374 406
  95 474 227 368 436 455 444 201 259 226 441 373 163 116 360 130 171 335
 120 403 165 445 231 473  46 174 291 405  89 244  37 283  75 401 424 449
 297 211 196 471  54 452 145 461 233 351 281 413 409 113  98 414 462 318
 234  97 419 107 402 320 194 276 220 447 103  58 271 386 273 159 253  44
  85 189 432 216 317 190 133 147 118  71 191 454 476 463 279 375  72 277
  16 131 398  41 428 477  50 326 150 397 329 101 204 321 141 261 258 418
  30  83 162 289  67 309 115 475 422 269 267 278 366 230 472 266 457 203
 340 225 399 383 124 294 313  32 350 288 460 167 331 260 337 459  36  42
  38 173 262 349 315  99 160 102 241 181 392  68 456 442 400  49 128 443
 356 334 394 479 395  52 369 154  91 287  34 166 182 149 207 353 377 161
 213 106 242 305 322 332 328 415 319 212 380  51 264 121 421 408 296 438
 390 156 448 257 308  63 221 157 367 256 254  80 359 199 164 347 108 205
 255 324  59 249 152 306 135  56  45 245 343  70 361 208  29 217  48  61
  47 263 453 327 312  65 298 175 407 458  53  81 295  90 186]
job_benefits: <StringArray>
[          'Stock Options (ESOPs), Free Meals, Remote First Work culture',
                             'Paid Time Off, Medical Cover, Annual Bonus',
             'Health Insurance, Flexible Hours, Work from Home Allowance',
 'Comprehensive Health Policy, Retirement Benefits, Soft Skills Training',
      'Performance Incentives, Skill Upskilling Allowance, Gadget Policy']
Length: 5, dtype: str
technical_domain: <StringArray>
[    'Core Applied Machine Learning',    'Frontend & Backend Engineering',
    'Cloud & Infrastructure Systems',    'Network & Information Security',
          'Enterprise Cloud Systems', 'Analytics & Business Intelligence']
Length: 6, dtype: str
interview_difficulty: <StringArray>
['Medium', 'Easy', 'Hard']
Length: 3, dtype: str
probation_period: <StringArray>
['3 Months', '6 Months']
Length: 2, dtype: str
shift_type: <StringArray>
['Flexible Shift', 'Day Shift', 'Night Shift']
Length: 3, dtype: str
is_active: [False  True]
career_growth_index: <StringArray>
['85%', '65%', '70%', '84%', '82%', '78%', '76%', '98%', '79%', '72%', '91%',
 '95%', '68%', '83%', '66%', '92%', '69%', '67%', '90%', '93%', '74%', '77%',
 '86%', '81%', '75%', '87%', '97%', '96%', '80%', '88%', '89%', '71%', '94%',
 '73%']
Length: 34, dtype: str

In [ ]:
df['location_city'].unique()

<StringArray>
['Delhi NCR',   'Gurgaon',      'Pune', 'Bangalore',   'Chennai',    'Mumbai',
 'Hyderabad',     'Noida']
Length: 8, dtype: str

In [ ]:
df['career_growth_index'].unique()

<StringArray>
['85%', '65%', '70%', '84%', '82%', '78%', '76%', '98%', '79%', '72%', '91%',
 '95%', '68%', '83%', '66%', '92%', '69%', '67%', '90%', '93%', '74%', '77%',
 '86%', '81%', '75%', '87%', '97%', '96%', '80%', '88%', '89%', '71%', '94%',
 '73%']
Length: 34, dtype: str

In [ ]:
df['probation_period'].unique()

<StringArray>
['3 Months', '6 Months']
Length: 2, dtype: str

In [ ]:
df['salary_currency'].unique()

<StringArray>
['INR']
Length: 1, dtype: str

In [ ]:
df['salary_maximum'].unique()

array([1696925, 1714068, 1235656, ...,  889572, 1204158, 1538666],
      shape=(95577,))

In [ ]:
df['shift_type'].unique()

<StringArray>
['Flexible Shift', 'Day Shift', 'Night Shift']
Length: 3, dtype: str

In [ ]:
df['skill_count'].unique()

array([6, 8, 7])

In [ ]:
df['source_platform'].unique()

<StringArray>
['LinkedIn', 'AmbitionBox', 'Glassdoor', 'Naukri.com', 'Indeed']
Length: 5, dtype: str

In [ ]:
df['stipend_amount'].unique()

array([32688, 30683, 39874, ..., 33123, 38895, 16496], shape=(28954,))

In [ ]:
df['technical_domain'].unique()

<StringArray>
[    'Core Applied Machine Learning',    'Frontend & Backend Engineering',
    'Cloud & Infrastructure Systems',    'Network & Information Security',
          'Enterprise Cloud Systems', 'Analytics & Business Intelligence']
Length: 6, dtype: str

HANDLING DUPLICATES

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df.duplicated(subset = ['job_title', 'job_category', 'location_city', 'company_name', 'experience_level'],keep= False)].sort_values(["company_name", "job_title"])

,job_title,job_category,company_name,company_size,industry,company_type,location_city,location_state,location_country,salary_minimum,...,application_deadline,source_platform,applicant_count,job_benefits,technical_domain,interview_difficulty,probation_period,shift_type,is_active,career_growth_index
69,AI Research Intern,AI / ML Engineering,Cognizant,"10,000+ employees",Information Technology,Top MNC,Pune,Maharashtra,India,455866,...,05-02-2026,AmbitionBox,218,"Health Insurance, Flexible Hours, Work from Ho...",Core Applied Machine Learning,Easy,3 Months,Day Shift,True,70%
502,AI Research Intern,AI / ML Engineering,Cognizant,"10,000+ employees",Information Technology,Top MNC,Pune,Maharashtra,India,467722,...,05-03-2026,AmbitionBox,414,"Paid Time Off, Medical Cover, Annual Bonus",Core Applied Machine Learning,Hard,6 Months,Flexible Shift,True,90%
553,AI Research Intern,AI / ML Engineering,Cognizant,"10,000+ employees",Information Technology,Top MNC,Chennai,Tamil Nadu,India,512264,...,16-04-2026,Naukri.com,30,"Health Insurance, Flexible Hours, Work from Ho...",Core Applied Machine Learning,Medium,3 Months,Day Shift,True,77%
806,AI Research Intern,AI / ML Engineering,Cognizant,"10,000+ employees",Information Technology,Top MNC,Delhi NCR,Delhi,India,422303,...,23-04-2026,Indeed,431,"Paid Time Off, Medical Cover, Annual Bonus",Core Applied Machine Learning,Hard,3 Months,Day Shift,False,81%
1194,AI Research Intern,AI / ML Engineering,Cognizant,"10,000+ employees",Information Technology,Top MNC,Hyderabad,Telangana,India,442067,...,21-02-2026,Indeed,459,"Performance Incentives, Skill Upskilling Allow...",Core Applied Machine Learning,Hard,6 Months,Day Shift,True,95%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97399,Web Development Intern,Web Development,Zomato,"1,000-5,000 employees",Information Technology,Tech Startup,Pune,Maharashtra,India,537830,...,09-06-2026,Indeed,252,"Performance Incentives, Skill Upskilling Allow...",Frontend & Backend Engineering,Medium,6 Months,Day Shift,True,79%
97936,Web Development Intern,Web Development,Zomato,"1,000-5,000 employees",Information Technology,Tech Startup,Mumbai,Maharashtra,India,486985,...,05-02-2026,Glassdoor,416,"Performance Incentives, Skill Upskilling Allow...",Frontend & Backend Engineering,Medium,3 Months,Day Shift,True,66%
98127,Web Development Intern,Web Development,Zomato,"1,000-5,000 employees",Information Technology,Tech Startup,Gurgaon,Haryana,India,535580,...,15-04-2026,Naukri.com,119,"Stock Options (ESOPs), Free Meals, Remote Firs...",Frontend & Backend Engineering,Medium,3 Months,Day Shift,False,97%
98346,Web Development Intern,Web Development,Zomato,"1,000-5,000 employees",Information Technology,Tech Startup,Chennai,Tamil Nadu,India,502639,...,11-05-2026,Glassdoor,318,"Performance Incentives, Skill Upskilling Allow...",Frontend & Backend Engineering,Medium,6 Months,Day Shift,True,72%
98871,Web Development Intern,Web Development,Zomato,"1,000-5,000 employees",Information Technology,Tech Startup,Chennai,Tamil Nadu,India,341277,...,29-06-2026,AmbitionBox,398,"Stock Options (ESOPs), Free Meals, Remote Firs...",Frontend & Backend Engineering,Medium,6 Months,Day Shift,True,74%

In [ ]:
df['career_growth_index'] = pd.to_numeric(df['career_growth_index'].astype('string').str.replace('%', '', regex = False), errors= 'coerce')
df['career_growth_index']

0        85
1        65
2        70
3        84
4        82
         ..
99995    80
99996    69
99997    70
99998    68
99999    95
Name: career_growth_index, Length: 100000, dtype: Int64

CHECKOUT MY CLEAN DATA

In [ ]:
df.shape

(100000, 32)

In [ ]:
df.info(verbose = True, show_counts= True)

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   job_title             100000 non-null  str
 1   job_category          100000 non-null  str
 2   company_name          100000 non-null  str
 3   company_size          100000 non-null  str
 4   industry              100000 non-null  str
 5   company_type          100000 non-null  str
 6   location_city         100000 non-null  str
 7   location_state        100000 non-null  str
 8   location_country      100000 non-null  str
 9   salary_minimum        100000 non-null  int64
 10  salary_maximum        100000 non-null  int64
 11  salary_currency       100000 non-null  str
 12  stipend_amount        100000 non-null  int64
 13  experience_level      100000 non-null  str
 14  experience_required   100000 non-null  str
 15  education_required    100000 non-null  str
 16  employment_type       100000 non-null  str
 17  contract_type         100000 non-null  str
 18  skills_extracted      100000 non-null  str
 19  skill_count           100000 non-null  int64
 20  job_description       100000 non-null  str
 21  posted_date           100000 non-null  str
 22  application_deadline  100000 non-null  str
 23  source_platform       100000 non-null  str
 24  applicant_count       100000 non-null  int64
 25  job_benefits          100000 non-null  str
 26  technical_domain      100000 non-null  str
 27  interview_difficulty  100000 non-null  str
 28  probation_period      100000 non-null  str
 29  shift_type            100000 non-null  str
 30  is_active             100000 non-null  bool
 31  career_growth_index   100000 non-null  Int64
dtypes: Int64(1), bool(1), int64(5), str(25)
memory usage: 23.8 MB

In [ ]:
df.columns.tolist()

['job_title',
 'job_category',
 'company_name',
 'company_size',
 'industry',
 'company_type',
 'location_city',
 'location_state',
 'location_country',
 'salary_minimum',
 'salary_maximum',
 'salary_currency',
 'stipend_amount',
 'experience_level',
 'experience_required',
 'education_required',
 'employment_type',
 'contract_type',
 'skills_extracted',
 'skill_count',
 'job_description',
 'posted_date',
 'application_deadline',
 'source_platform',
 'applicant_count',
 'job_benefits',
 'technical_domain',
 'interview_difficulty',
 'probation_period',
 'shift_type',
 'is_active',
 'career_growth_index']

In [ ]:
df.isna().sum()

job_title               0
job_category            0
company_name            0
company_size            0
industry                0
company_type            0
location_city           0
location_state          0
location_country        0
salary_minimum          0
salary_maximum          0
salary_currency         0
stipend_amount          0
experience_level        0
experience_required     0
education_required      0
employment_type         0
contract_type           0
skills_extracted        0
skill_count             0
job_description         0
posted_date             0
application_deadline    0
source_platform         0
applicant_count         0
job_benefits            0
technical_domain        0
interview_difficulty    0
probation_period        0
shift_type              0
is_active               0
career_growth_index     0
dtype: int64

In [ ]:
for col in df.columns:
    print("\n ")
    print(f"{col}: {df[col].unique()}")

job_title : <StringArray>
[  'Machine Learning Engineer',        'Full Stack Developer',
      'Web Development Intern',               'DevOps Intern',
       'Cybersecurity Analyst',   'Site Reliability Engineer',
 'Cloud Infrastructure Intern',       'Data Analytics Intern',
        'Azure Cloud Engineer',           'Platform Engineer',
             'React Developer',               'Data Engineer',
          'Penetration Tester',                 'SOC Analyst',
           'Frontend Engineer',       'Cloud DevOps Engineer',
              'Data Scientist',     'AWS Solutions Architect',
            'Business Analyst',          'AI Research Intern',
    'Computer Vision Engineer',             'Security Intern',
               'LLM Developer',           'Backend Developer']
Length: 24, dtype: str


job_category : <StringArray>
['AI / ML Engineering',     'Web Development',         'DevOps Core',
       'Cybersecurity',  'Cloud Architecture',        'Data Science']
Length: 6, dtype: str


company_name : <StringArray>
[          'TCS',  'Ola Electric',     'Cognizant',       'Infosys',
        'Swiggy',       'HCLTech',         'Paytm',        'Zomato',
          'Cred',         'Wipro', 'Tech Mahindra',      'Razorpay']
Length: 12, dtype: str


company_size : <StringArray>
[    '10,000+ employees', '1,000-5,000 employees',     '100-500 employees',
   '500-1,000 employees']
Length: 4, dtype: str


industry : <StringArray>
['Information Technology']
Length: 1, dtype: str


company_type : <StringArray>
['Top MNC', 'Tech Startup', 'Fintech Unicorn']
Length: 3, dtype: str


location_city : <StringArray>
['Delhi NCR',   'Gurgaon',      'Pune', 'Bangalore',   'Chennai',    'Mumbai',
 'Hyderabad',     'Noida']
Length: 8, dtype: str


location_state : <StringArray>
[        'Delhi',       'Haryana',   'Maharashtra',     'Karnataka',
    'Tamil Nadu',     'Telangana', 'Uttar Pradesh']
Length: 7, dtype: str


location_country : <StringArray>
['India']
Length: 1, dtype: str


salary_minimum : [303344 326766 549068 ... 311878 340435 592542]


salary_maximum : [1696925 1714068 1235656 ...  889572 1204158 1538666]


salary_currency : <StringArray>
['INR']
Length: 1, dtype: str


stipend_amount : [32688 30683 39874 ... 33123 38895 16496]


experience_level : <StringArray>
['Mid-Senior Level', 'Freshers / Entry Level']
Length: 2, dtype: str


experience_required : <StringArray>
['2-4 Years', '0-1 Years']
Length: 2, dtype: str


education_required : <StringArray>
['MCA / MSc', 'Bachelor's Degree', 'B.E. / B.Tech']
Length: 3, dtype: str


employment_type : <StringArray>
['Full-time', 'Internship']
Length: 2, dtype: str


contract_type : <StringArray>
['Permanent', 'Contractual']
Length: 2, dtype: str


skills_extracted : <StringArray>
[     'Python, PyTorch, TensorFlow, Scikit-Learn, OpenAI API, HuggingFace',
   'HTML, CSS, JavaScript, React, Node.js, Express, MongoDB, Tailwind CSS',
               'Docker, Kubernetes, Jenkins, CI/CD, Linux, Terraform, Git',
 'Network Security, Wireshark, Metasploit, Linux, OWASP Top 10, Firewalls',
           'AWS, Azure, CloudFormation, IAM, EC2, S3, Architecture Design',
                    'Python, SQL, Tableau, Power BI, Pandas, NumPy, Excel']
Length: 6, dtype: str


skill_count : [6 8 7]


job_description : <StringArray>
[  '<p>We are hiring a passionate Machine Learning Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
        '<p>We are hiring a passionate Full Stack Developer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
      '<p>We are hiring a passionate Web Development Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
               '<p>We are hiring a passionate DevOps Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
       '<p>We are hiring a passionate Cybersecurity Analyst to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
   '<p>We are hiring a passionate Site Reliability Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
 '<p>We are hiring a passionate Cloud Infrastructure Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
       '<p>We are hiring a passionate Data Analytics Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
        '<p>We are hiring a passionate Azure Cloud Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
           '<p>We are hiring a passionate Platform Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
             '<p>We are hiring a passionate React Developer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
               '<p>We are hiring a passionate Data Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
          '<p>We are hiring a passionate Penetration Tester to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
                 '<p>We are hiring a passionate SOC Analyst to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
           '<p>We are hiring a passionate Frontend Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
       '<p>We are hiring a passionate Cloud DevOps Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
              '<p>We are hiring a passionate Data Scientist to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
     '<p>We are hiring a passionate AWS Solutions Architect to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
            '<p>We are hiring a passionate Business Analyst to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
          '<p>We are hiring a passionate AI Research Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
    '<p>We are hiring a passionate Computer Vision Engineer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
             '<p>We are hiring a passionate Security Intern to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
               '<p>We are hiring a passionate LLM Developer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>',
           '<p>We are hiring a passionate Backend Developer to join our engineering cluster. Hands-on experience with core tech workflows preferred.</p>']
Length: 24, dtype: str


posted_date : <StringArray>
['14-02-2026', '30-01-2026', '08-01-2026', '15-05-2026', '23-05-2026',
 '03-01-2026', '11-03-2026', '28-02-2026', '21-05-2026', '28-05-2026',
 ...
 '10-05-2026', '20-05-2026', '12-01-2026', '16-04-2026', '07-02-2026',
 '08-03-2026', '10-04-2026', '16-03-2026', '12-02-2026', '27-02-2026']
Length: 150, dtype: str


application_deadline : <StringArray>
['16-03-2026', '01-03-2026', '07-02-2026', '14-06-2026', '22-06-2026',
 '02-02-2026', '10-04-2026', '30-03-2026', '20-06-2026', '27-06-2026',
 ...
 '09-06-2026', '19-06-2026', '11-02-2026', '16-05-2026', '09-03-2026',
 '07-04-2026', '10-05-2026', '15-04-2026', '14-03-2026', '29-03-2026']
Length: 150, dtype: str


source_platform : <StringArray>
['LinkedIn', 'AmbitionBox', 'Glassdoor', 'Naukri.com', 'Indeed']
Length: 5, dtype: str


applicant_count : [193 465  77 387  27 385 243 364 311 210 117  35 134 451  22 314 177 362
 285  40 218 304 346 468 416 450 434  23 219 198 358  82 224 202  74 372
 138  84 183 388 391 209 195 341  64 433 378 354 381 429 384 365 109 184
  28  79 423 127 136 170 357  62  93 112 310 469 425 137 275 248  15 379
  18 467 439 168 206 299 348 214 142 420 345 187 466 323 352 240 282  26
 185 426 437 417 431 247  92 228 292 302 325 236 126 427  86 114 143 178
 338 105 111  60 110 197 151 286 180 139 252 280 355 371 122 268  88 464
  96 158 200 330 239  24 303 232  25 290  73  43 172 146 119 144 246 435
 300  21  69 470 389 237  20 376  55 235 270  31 284 307  39  57 478 274
 344 446  87 148  78 336 100 430 412 404 192 316  33  19 153 272  17 410
 411 155  94 440 229 223 396 333  66 342 188 301 132 250 251 293 370 382
 104 125 179  76 176 129 222 169 363 238 215 393 265 339 140 123 374 406
  95 474 227 368 436 455 444 201 259 226 441 373 163 116 360 130 171 335
 120 403 165 445 231 473  46 174 291 405  89 244  37 283  75 401 424 449
 297 211 196 471  54 452 145 461 233 351 281 413 409 113  98 414 462 318
 234  97 419 107 402 320 194 276 220 447 103  58 271 386 273 159 253  44
  85 189 432 216 317 190 133 147 118  71 191 454 476 463 279 375  72 277
  16 131 398  41 428 477  50 326 150 397 329 101 204 321 141 261 258 418
  30  83 162 289  67 309 115 475 422 269 267 278 366 230 472 266 457 203
 340 225 399 383 124 294 313  32 350 288 460 167 331 260 337 459  36  42
  38 173 262 349 315  99 160 102 241 181 392  68 456 442 400  49 128 443
 356 334 394 479 395  52 369 154  91 287  34 166 182 149 207 353 377 161
 213 106 242 305 322 332 328 415 319 212 380  51 264 121 421 408 296 438
 390 156 448 257 308  63 221 157 367 256 254  80 359 199 164 347 108 205
 255 324  59 249 152 306 135  56  45 245 343  70 361 208  29 217  48  61
  47 263 453 327 312  65 298 175 407 458  53  81 295  90 186]


job_benefits : <StringArray>
[          'Stock Options (ESOPs), Free Meals, Remote First Work culture',
                             'Paid Time Off, Medical Cover, Annual Bonus',
             'Health Insurance, Flexible Hours, Work from Home Allowance',
 'Comprehensive Health Policy, Retirement Benefits, Soft Skills Training',
      'Performance Incentives, Skill Upskilling Allowance, Gadget Policy']
Length: 5, dtype: str


technical_domain : <StringArray>
[    'Core Applied Machine Learning',    'Frontend & Backend Engineering',
    'Cloud & Infrastructure Systems',    'Network & Information Security',
          'Enterprise Cloud Systems', 'Analytics & Business Intelligence']
Length: 6, dtype: str


interview_difficulty : <StringArray>
['Medium', 'Easy', 'Hard']
Length: 3, dtype: str


probation_period : <StringArray>
['3 Months', '6 Months']
Length: 2, dtype: str


shift_type : <StringArray>
['Flexible Shift', 'Day Shift', 'Night Shift']
Length: 3, dtype: str


is_active : [False  True]


career_growth_index : <IntegerArray>
[85, 65, 70, 84, 82, 78, 76, 98, 79, 72, 91, 95, 68, 83, 66, 92, 69, 67, 90,
 93, 74, 77, 86, 81, 75, 87, 97, 96, 80, 88, 89, 71, 94, 73]
Length: 34, dtype: Int64

TRANSFER CLEAN DATA TO SQL

In [ ]:
from sqlalchemy import create_engine, URL

connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="abrahman95",
    host="localhost",
    port=3306,
    database="job_market_analysis"
)

engine = create_engine(connection_url)

with engine.connect() as connection:
    print("MySQL connected successfully!")

MySQL connected successfully!

In [ ]:
df.to_sql(
    name="job_postings",
    con=engine,
    if_exists="replace",
    index=False
)

100000